/*
 * IONOS Cloud - Object Storage Management API
 * Object Storage Management API is a RESTful API that manages the object storage service configuration for IONOS Cloud. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.objectstoragemanagement.api;

import com.ionoscloud.objectstoragemanagement.ApiCallback;
import com.ionoscloud.objectstoragemanagement.ApiClient;
import com.ionoscloud.objectstoragemanagement.ApiException;
import com.ionoscloud.objectstoragemanagement.ApiResponse;
import com.ionoscloud.objectstoragemanagement.Configuration;
import com.ionoscloud.objectstoragemanagement.Pair;
import com.ionoscloud.objectstoragemanagement.ProgressRequestBody;
import com.ionoscloud.objectstoragemanagement.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.ionoscloud.objectstoragemanagement.model.AccessKeyCreate;
import com.ionoscloud.objectstoragemanagement.model.AccessKeyEnsure;
import com.ionoscloud.objectstoragemanagement.model.AccessKeyRead;
import com.ionoscloud.objectstoragemanagement.model.AccessKeyReadList;
import com.ionoscloud.objectstoragemanagement.model.Error;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AccesskeysApi {
    private ApiClient localVarApiClient;

    public AccesskeysApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AccesskeysApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    /**
     * Build call for accesskeysDelete
     * @param accesskeyId The ID (UUID) of the AccessKey. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Deleting AccessKey was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call accesskeysDeleteCall(UUID accesskeyId, final ApiCallback<Void> _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/accesskeys/{accesskeyId}"
            .replaceAll("\\{" + "accesskeyId" + "\\}", localVarApiClient.escapeString(accesskeyId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "tokenAuth" };
        return localVarApiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call accesskeysDeleteValidateBeforeCall(UUID accesskeyId, final ApiCallback<Void> _callback) throws ApiException {
        
        // verify the required parameter 'accesskeyId' is set
        if (accesskeyId == null) {
            throw new ApiException("Missing the required parameter 'accesskeyId' when calling accesskeysDelete(Async)");
        }
        

        okhttp3.Call localVarCall = accesskeysDeleteCall(accesskeyId, _callback);
        return localVarCall;

    }

    /**
     * Delete AccessKey
     * Deletes the specified AccessKey.
     * @param accesskeyId The ID (UUID) of the AccessKey. (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Deleting AccessKey was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public void accesskeysDelete(UUID accesskeyId) throws ApiException {
        accesskeysDeleteWithHttpInfo(accesskeyId);
    }

    /**
     * Delete AccessKey
     * Deletes the specified AccessKey.
     * @param accesskeyId The ID (UUID) of the AccessKey. (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Deleting AccessKey was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> accesskeysDeleteWithHttpInfo(UUID accesskeyId) throws ApiException {
        okhttp3.Call localVarCall = accesskeysDeleteValidateBeforeCall(accesskeyId, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Delete AccessKey (asynchronously)
     * Deletes the specified AccessKey.
     * @param accesskeyId The ID (UUID) of the AccessKey. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Deleting AccessKey was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call accesskeysDeleteAsync(UUID accesskeyId, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = accesskeysDeleteValidateBeforeCall(accesskeyId, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for accesskeysFindById
     * @param accesskeyId The ID (UUID) of the AccessKey. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Getting AccessKey was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call accesskeysFindByIdCall(UUID accesskeyId, final ApiCallback<AccessKeyRead> _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/accesskeys/{accesskeyId}"
            .replaceAll("\\{" + "accesskeyId" + "\\}", localVarApiClient.escapeString(accesskeyId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "tokenAuth" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call accesskeysFindByIdValidateBeforeCall(UUID accesskeyId, final ApiCallback<AccessKeyRead> _callback) throws ApiException {
        
        // verify the required parameter 'accesskeyId' is set
        if (accesskeyId == null) {
            throw new ApiException("Missing the required parameter 'accesskeyId' when calling accesskeysFindById(Async)");
        }
        

        okhttp3.Call localVarCall = accesskeysFindByIdCall(accesskeyId, _callback);
        return localVarCall;

    }

    /**
     * Retrieve AccessKey
     * Returns the AccessKey by ID.
     * @param accesskeyId The ID (UUID) of the AccessKey. (required)
     * @return AccessKeyRead
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Getting AccessKey was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public AccessKeyRead accesskeysFindById(UUID accesskeyId) throws ApiException {
        ApiResponse<AccessKeyRead> localVarResp = accesskeysFindByIdWithHttpInfo(accesskeyId);
        return localVarResp.getData();
    }

    /**
     * Retrieve AccessKey
     * Returns the AccessKey by ID.
     * @param accesskeyId The ID (UUID) of the AccessKey. (required)
     * @return ApiResponse&lt;AccessKeyRead&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Getting AccessKey was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AccessKeyRead> accesskeysFindByIdWithHttpInfo(UUID accesskeyId) throws ApiException {
        okhttp3.Call localVarCall = accesskeysFindByIdValidateBeforeCall(accesskeyId, null);
        Type localVarReturnType = new TypeToken<AccessKeyRead>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve AccessKey (asynchronously)
     * Returns the AccessKey by ID.
     * @param accesskeyId The ID (UUID) of the AccessKey. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Getting AccessKey was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call accesskeysFindByIdAsync(UUID accesskeyId, final ApiCallback<AccessKeyRead> _callback) throws ApiException {

        okhttp3.Call localVarCall = accesskeysFindByIdValidateBeforeCall(accesskeyId, _callback);
        Type localVarReturnType = new TypeToken<AccessKeyRead>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for accesskeysGet
     * @param offset The first element (of the total list of elements) to include in the response. Use together with limit for pagination. (optional, default to 0)
     * @param limit The maximum number of elements to return. Use together with offset for pagination. (optional, default to 100)
     * @param filterAccesskeyId The accesskey ID to filter by. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned all requested Accesskeys successfully.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call accesskeysGetCall(Integer offset, Integer limit, String filterAccesskeyId, final ApiCallback<AccessKeyReadList> _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/accesskeys";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (filterAccesskeyId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("filter.accesskeyId", filterAccesskeyId));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "tokenAuth" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call accesskeysGetValidateBeforeCall(Integer offset, Integer limit, String filterAccesskeyId, final ApiCallback<AccessKeyReadList> _callback) throws ApiException {
        

        okhttp3.Call localVarCall = accesskeysGetCall(offset, limit, filterAccesskeyId, _callback);
        return localVarCall;

    }

    /**
     * Retrieve all Accesskeys
     * This endpoint enables retrieving all Accesskeys using pagination and optional filters. 
     * @param offset The first element (of the total list of elements) to include in the response. Use together with limit for pagination. (optional, default to 0)
     * @param limit The maximum number of elements to return. Use together with offset for pagination. (optional, default to 100)
     * @param filterAccesskeyId The accesskey ID to filter by. (optional)
     * @return AccessKeyReadList
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned all requested Accesskeys successfully.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public AccessKeyReadList accesskeysGet(Integer offset, Integer limit, String filterAccesskeyId) throws ApiException {
        ApiResponse<AccessKeyReadList> localVarResp = accesskeysGetWithHttpInfo(offset, limit, filterAccesskeyId);
        return localVarResp.getData();
    }

    /**
     * Retrieve all Accesskeys
     * This endpoint enables retrieving all Accesskeys using pagination and optional filters. 
     * @param offset The first element (of the total list of elements) to include in the response. Use together with limit for pagination. (optional, default to 0)
     * @param limit The maximum number of elements to return. Use together with offset for pagination. (optional, default to 100)
     * @param filterAccesskeyId The accesskey ID to filter by. (optional)
     * @return ApiResponse&lt;AccessKeyReadList&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned all requested Accesskeys successfully.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AccessKeyReadList> accesskeysGetWithHttpInfo(Integer offset, Integer limit, String filterAccesskeyId) throws ApiException {
        okhttp3.Call localVarCall = accesskeysGetValidateBeforeCall(offset, limit, filterAccesskeyId, null);
        Type localVarReturnType = new TypeToken<AccessKeyReadList>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve all Accesskeys (asynchronously)
     * This endpoint enables retrieving all Accesskeys using pagination and optional filters. 
     * @param offset The first element (of the total list of elements) to include in the response. Use together with limit for pagination. (optional, default to 0)
     * @param limit The maximum number of elements to return. Use together with offset for pagination. (optional, default to 100)
     * @param filterAccesskeyId The accesskey ID to filter by. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned all requested Accesskeys successfully.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call accesskeysGetAsync(Integer offset, Integer limit, String filterAccesskeyId, final ApiCallback<AccessKeyReadList> _callback) throws ApiException {

        okhttp3.Call localVarCall = accesskeysGetValidateBeforeCall(offset, limit, filterAccesskeyId, _callback);
        Type localVarReturnType = new TypeToken<AccessKeyReadList>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for accesskeysPost
     * @param accessKeyCreate AccessKey to create. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> AccessKey successfully created. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> ### Unsupported Media Type The request has an unsupported media type.  </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> ### Unprocessable Entity The request was well-formed but was unable to be followed due to semantic errors.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call accesskeysPostCall(AccessKeyCreate accessKeyCreate, final ApiCallback<AccessKeyRead> _callback) throws ApiException {
        Object localVarPostBody = accessKeyCreate;

        // create path and map variables
        String localVarPath = "/accesskeys";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "tokenAuth" };
        return localVarApiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call accesskeysPostValidateBeforeCall(AccessKeyCreate accessKeyCreate, final ApiCallback<AccessKeyRead> _callback) throws ApiException {
        
        // verify the required parameter 'accessKeyCreate' is set
        if (accessKeyCreate == null) {
            throw new ApiException("Missing the required parameter 'accessKeyCreate' when calling accesskeysPost(Async)");
        }
        

        okhttp3.Call localVarCall = accesskeysPostCall(accessKeyCreate, _callback);
        return localVarCall;

    }

    /**
     * Create AccessKey
     * Creates a new AccessKey.  The full AccessKey needs to be provided to create the object. Optional data will be filled with defaults or left empty. 
     * @param accessKeyCreate AccessKey to create. (required)
     * @return AccessKeyRead
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> AccessKey successfully created. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> ### Unsupported Media Type The request has an unsupported media type.  </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> ### Unprocessable Entity The request was well-formed but was unable to be followed due to semantic errors.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public AccessKeyRead accesskeysPost(AccessKeyCreate accessKeyCreate) throws ApiException {
        ApiResponse<AccessKeyRead> localVarResp = accesskeysPostWithHttpInfo(accessKeyCreate);
        return localVarResp.getData();
    }

    /**
     * Create AccessKey
     * Creates a new AccessKey.  The full AccessKey needs to be provided to create the object. Optional data will be filled with defaults or left empty. 
     * @param accessKeyCreate AccessKey to create. (required)
     * @return ApiResponse&lt;AccessKeyRead&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> AccessKey successfully created. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> ### Unsupported Media Type The request has an unsupported media type.  </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> ### Unprocessable Entity The request was well-formed but was unable to be followed due to semantic errors.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AccessKeyRead> accesskeysPostWithHttpInfo(AccessKeyCreate accessKeyCreate) throws ApiException {
        okhttp3.Call localVarCall = accesskeysPostValidateBeforeCall(accessKeyCreate, null);
        Type localVarReturnType = new TypeToken<AccessKeyRead>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create AccessKey (asynchronously)
     * Creates a new AccessKey.  The full AccessKey needs to be provided to create the object. Optional data will be filled with defaults or left empty. 
     * @param accessKeyCreate AccessKey to create. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> AccessKey successfully created. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> ### Unsupported Media Type The request has an unsupported media type.  </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> ### Unprocessable Entity The request was well-formed but was unable to be followed due to semantic errors.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call accesskeysPostAsync(AccessKeyCreate accessKeyCreate, final ApiCallback<AccessKeyRead> _callback) throws ApiException {

        okhttp3.Call localVarCall = accesskeysPostValidateBeforeCall(accessKeyCreate, _callback);
        Type localVarReturnType = new TypeToken<AccessKeyRead>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for accesskeysPut
     * @param accesskeyId The ID (UUID) of the AccessKey. (required)
     * @param accessKeyEnsure update AccessKey (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> AccessKey successfully updated. </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> AccessKey successfully ensured. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> ### Conflict The UUID is already taken by another party, follow the guides to generate UUIDs uniquely.  </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> ### Unsupported Media Type The request has an unsupported media type.  </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> ### Unprocessable Entity The request was well-formed but was unable to be followed due to semantic errors.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call accesskeysPutCall(UUID accesskeyId, AccessKeyEnsure accessKeyEnsure, final ApiCallback<AccessKeyRead> _callback) throws ApiException {
        Object localVarPostBody = accessKeyEnsure;

        // create path and map variables
        String localVarPath = "/accesskeys/{accesskeyId}"
            .replaceAll("\\{" + "accesskeyId" + "\\}", localVarApiClient.escapeString(accesskeyId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "tokenAuth" };
        return localVarApiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call accesskeysPutValidateBeforeCall(UUID accesskeyId, AccessKeyEnsure accessKeyEnsure, final ApiCallback<AccessKeyRead> _callback) throws ApiException {
        
        // verify the required parameter 'accesskeyId' is set
        if (accesskeyId == null) {
            throw new ApiException("Missing the required parameter 'accesskeyId' when calling accesskeysPut(Async)");
        }
        
        // verify the required parameter 'accessKeyEnsure' is set
        if (accessKeyEnsure == null) {
            throw new ApiException("Missing the required parameter 'accessKeyEnsure' when calling accesskeysPut(Async)");
        }
        

        okhttp3.Call localVarCall = accesskeysPutCall(accesskeyId, accessKeyEnsure, _callback);
        return localVarCall;

    }

    /**
     * Ensure AccessKey
     * Ensures that the AccessKey with the provided ID is created or modified. The full AccessKey needs to be provided to ensure (either update or create) the AccessKey. Non present data will only be filled with defaults or left empty, but not take previous values into consideration. 
     * @param accesskeyId The ID (UUID) of the AccessKey. (required)
     * @param accessKeyEnsure update AccessKey (required)
     * @return AccessKeyRead
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> AccessKey successfully updated. </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> AccessKey successfully ensured. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> ### Conflict The UUID is already taken by another party, follow the guides to generate UUIDs uniquely.  </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> ### Unsupported Media Type The request has an unsupported media type.  </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> ### Unprocessable Entity The request was well-formed but was unable to be followed due to semantic errors.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public AccessKeyRead accesskeysPut(UUID accesskeyId, AccessKeyEnsure accessKeyEnsure) throws ApiException {
        ApiResponse<AccessKeyRead> localVarResp = accesskeysPutWithHttpInfo(accesskeyId, accessKeyEnsure);
        return localVarResp.getData();
    }

    /**
     * Ensure AccessKey
     * Ensures that the AccessKey with the provided ID is created or modified. The full AccessKey needs to be provided to ensure (either update or create) the AccessKey. Non present data will only be filled with defaults or left empty, but not take previous values into consideration. 
     * @param accesskeyId The ID (UUID) of the AccessKey. (required)
     * @param accessKeyEnsure update AccessKey (required)
     * @return ApiResponse&lt;AccessKeyRead&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> AccessKey successfully updated. </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> AccessKey successfully ensured. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> ### Conflict The UUID is already taken by another party, follow the guides to generate UUIDs uniquely.  </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> ### Unsupported Media Type The request has an unsupported media type.  </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> ### Unprocessable Entity The request was well-formed but was unable to be followed due to semantic errors.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AccessKeyRead> accesskeysPutWithHttpInfo(UUID accesskeyId, AccessKeyEnsure accessKeyEnsure) throws ApiException {
        okhttp3.Call localVarCall = accesskeysPutValidateBeforeCall(accesskeyId, accessKeyEnsure, null);
        Type localVarReturnType = new TypeToken<AccessKeyRead>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Ensure AccessKey (asynchronously)
     * Ensures that the AccessKey with the provided ID is created or modified. The full AccessKey needs to be provided to ensure (either update or create) the AccessKey. Non present data will only be filled with defaults or left empty, but not take previous values into consideration. 
     * @param accesskeyId The ID (UUID) of the AccessKey. (required)
     * @param accessKeyEnsure update AccessKey (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> AccessKey successfully updated. </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> AccessKey successfully ensured. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> ### Conflict The UUID is already taken by another party, follow the guides to generate UUIDs uniquely.  </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> ### Unsupported Media Type The request has an unsupported media type.  </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> ### Unprocessable Entity The request was well-formed but was unable to be followed due to semantic errors.  </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ### Too Many Requests The user has sent too many requests in a given amount of time.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> ### Service Unavailable The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> ### Unexpected Internal Server Error An unexpected internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call accesskeysPutAsync(UUID accesskeyId, AccessKeyEnsure accessKeyEnsure, final ApiCallback<AccessKeyRead> _callback) throws ApiException {

        okhttp3.Call localVarCall = accesskeysPutValidateBeforeCall(accesskeyId, accessKeyEnsure, _callback);
        Type localVarReturnType = new TypeToken<AccessKeyRead>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for accesskeysRenew
     * @param accesskeyId The ID (UUID) of the AccessKey that should be ensured. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> AccessKey successfully updated. </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> AccessKey successfully ensured. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> ### Conflict The UUID is already taken by another party, follow the guides to generate UUIDs uniquely.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call accesskeysRenewCall(UUID accesskeyId, final ApiCallback<AccessKeyRead> _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/accesskeys/{accesskeyId}/renew"
            .replaceAll("\\{" + "accesskeyId" + "\\}", localVarApiClient.escapeString(accesskeyId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "tokenAuth" };
        return localVarApiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call accesskeysRenewValidateBeforeCall(UUID accesskeyId, final ApiCallback<AccessKeyRead> _callback) throws ApiException {
        
        // verify the required parameter 'accesskeyId' is set
        if (accesskeyId == null) {
            throw new ApiException("Missing the required parameter 'accesskeyId' when calling accesskeysRenew(Async)");
        }
        

        okhttp3.Call localVarCall = accesskeysRenewCall(accesskeyId, _callback);
        return localVarCall;

    }

    /**
     * Ensure AccessKey
     * Renew will replace the existing secret access key with a new one. 
     * @param accesskeyId The ID (UUID) of the AccessKey that should be ensured. (required)
     * @return AccessKeyRead
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> AccessKey successfully updated. </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> AccessKey successfully ensured. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> ### Conflict The UUID is already taken by another party, follow the guides to generate UUIDs uniquely.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public AccessKeyRead accesskeysRenew(UUID accesskeyId) throws ApiException {
        ApiResponse<AccessKeyRead> localVarResp = accesskeysRenewWithHttpInfo(accesskeyId);
        return localVarResp.getData();
    }

    /**
     * Ensure AccessKey
     * Renew will replace the existing secret access key with a new one. 
     * @param accesskeyId The ID (UUID) of the AccessKey that should be ensured. (required)
     * @return ApiResponse&lt;AccessKeyRead&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> AccessKey successfully updated. </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> AccessKey successfully ensured. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> ### Conflict The UUID is already taken by another party, follow the guides to generate UUIDs uniquely.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AccessKeyRead> accesskeysRenewWithHttpInfo(UUID accesskeyId) throws ApiException {
        okhttp3.Call localVarCall = accesskeysRenewValidateBeforeCall(accesskeyId, null);
        Type localVarReturnType = new TypeToken<AccessKeyRead>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Ensure AccessKey (asynchronously)
     * Renew will replace the existing secret access key with a new one. 
     * @param accesskeyId The ID (UUID) of the AccessKey that should be ensured. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> AccessKey successfully updated. </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> AccessKey successfully ensured. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> ### Not Allowed The user issuing the request does not have the needed permissions.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> ### Conflict The UUID is already taken by another party, follow the guides to generate UUIDs uniquely.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call accesskeysRenewAsync(UUID accesskeyId, final ApiCallback<AccessKeyRead> _callback) throws ApiException {

        okhttp3.Call localVarCall = accesskeysRenewValidateBeforeCall(accesskeyId, _callback);
        Type localVarReturnType = new TypeToken<AccessKeyRead>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
