/*
 * IONOS Cloud - Object Storage Management API
 * Object Storage Management API is a RESTful API that manages the object storage service configuration for IONOS Cloud. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.objectstoragemanagement;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-25T14:47:08.560494Z[Etc/UTC]")
public class Configuration {
    public static final String IONOS_USERNAME_ENV_VAR = "IONOS_USERNAME";
    public static final String IONOS_PASSWORD_ENV_VAR = "IONOS_PASSWORD";
    public static final String IONOS_TOKEN_ENV_VAR    = "IONOS_TOKEN";
    public static final String IONOS_API_URL_ENV_VAR  = "IONOS_API_URL";

    public static final String DEFAULT_IONOS_SERVER_URL = "https://s3.ionos.com";
    public static final String DEFAULT_IONOS_BASE_PATH  = "";
    public static final String IONOS_SERVER_URLs[] = new String[] {
        "https://s3.ionos.com",
    };

    private static ApiClient defaultApiClient = new ApiClient();

    /**
     * Get the default API client, which would be used when creating API
     * instances without providing an API client.
     *
     * @return Default API client
     */
    public static ApiClient getDefaultApiClient() {
        return defaultApiClient;
    }

    /**
     * Set the default API client, which would be used when creating API
     * instances without providing an API client.
     *
     * @param apiClient API client
     */
    public static void setDefaultApiClient(ApiClient apiClient) {
        defaultApiClient = apiClient;
    }
}
