/*
 * IONOS Cloud - Object Storage Management API
 * Object Storage Management API is a RESTful API that manages the object storage service configuration for IONOS Cloud. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.objectstoragemanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ionoscloud.objectstoragemanagement.model.AccessKeyRead;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * AccessKeyReadListAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-26T11:50:15.750085Z[Etc/UTC]")

public class AccessKeyReadListAllOf {
  
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;


  /**
   * The type of the resource.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    COLLECTION("collection");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {

      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;


  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private String href;


  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  private List<AccessKeyRead> items = null;

  

  public AccessKeyReadListAllOf id(UUID id) {
    
    this.id = id;
    return this;
  }

   /**
   * ID of the list of AccessKey resources.
   * @return id
  **/
  @ApiModelProperty(example = "5cd907ee-6b6a-5e3a-abaf-5c2edd01d78c", required = true, value = "ID of the list of AccessKey resources.")

  public UUID getId() {
    return id;
  }


  public void setId(UUID id) {
    this.id = id;
  }



  public AccessKeyReadListAllOf type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * The type of the resource.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "The type of the resource.")

  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }



  public AccessKeyReadListAllOf href(String href) {
    
    this.href = href;
    return this;
  }

   /**
   * The URL of the list of AccessKey resources.
   * @return href
  **/
  @ApiModelProperty(example = "/accesskeys", required = true, value = "The URL of the list of AccessKey resources.")

  public String getHref() {
    return href;
  }


  public void setHref(String href) {
    this.href = href;
  }



  public AccessKeyReadListAllOf items(List<AccessKeyRead> items) {
    
    this.items = items;
    return this;
  }

  public AccessKeyReadListAllOf addItemsItem(AccessKeyRead itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<AccessKeyRead>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * The list of AccessKey resources.
   * @return items
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The list of AccessKey resources.")

  public List<AccessKeyRead> getItems() {
    return items;
  }


  public void setItems(List<AccessKeyRead> items) {
    this.items = items;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessKeyReadListAllOf accessKeyReadListAllOf = (AccessKeyReadListAllOf) o;
    return Objects.equals(this.id, accessKeyReadListAllOf.id) && Objects.equals(this.type, accessKeyReadListAllOf.type) && Objects.equals(this.href, accessKeyReadListAllOf.href) && Objects.equals(this.items, accessKeyReadListAllOf.items);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessKeyReadListAllOf {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");

    sb.append("    type: ").append(toIndentedString(type)).append("\n");

    sb.append("    href: ").append(toIndentedString(href)).append("\n");

    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

