/*
 * IONOS Cloud - Object Storage Management API
 * Object Storage Management API is a RESTful API that manages the object storage service configuration for IONOS Cloud. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.objectstoragemanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Per user access key. 
 */
@ApiModel(description = "Per user access key. ")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-26T16:06:24.400363Z[Etc/UTC]")

public class AccessKey {
  
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;


  public static final String SERIALIZED_NAME_ACCESS_KEY = "accessKey";
  @SerializedName(SERIALIZED_NAME_ACCESS_KEY)
  private String accessKey;


  public static final String SERIALIZED_NAME_SECRET_KEY = "secretKey";
  @SerializedName(SERIALIZED_NAME_SECRET_KEY)
  private String secretKey;


  public static final String SERIALIZED_NAME_CANONICAL_USER_ID = "canonicalUserId";
  @SerializedName(SERIALIZED_NAME_CANONICAL_USER_ID)
  private String canonicalUserId;


  public static final String SERIALIZED_NAME_CONTRACT_USER_ID = "contractUserId";
  @SerializedName(SERIALIZED_NAME_CONTRACT_USER_ID)
  private String contractUserId;

  

  public AccessKey description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Description of the Access key.
   * @return description
  **/
  @ApiModelProperty(example = "Access key details", required = true, value = "Description of the Access key.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }



   /**
   * Access key metadata is a string of 92 characters.
   * @return accessKey
  **/
  @ApiModelProperty(example = "00000Du4KiV8A1tGUbjI2Ky1YmXqXnCpaQpgWw6_1V5fhMPRnAAAAAEIkfcQAAAAAAiR9xAioHCB_FWuNJ4un864Pouw", required = true, value = "Access key metadata is a string of 92 characters.")

  public String getAccessKey() {
    return accessKey;
  }


  public void setAccessKey(String accessKey) {
    this.accessKey = accessKey;
  }



   /**
   * The secret key of the Access key.
   * @return secretKey
  **/
  @ApiModelProperty(example = "tFVkUARsoeCdntQs2jVSyGG6TMPfPZ+ghnsWj/gG", required = true, value = "The secret key of the Access key.")

  public String getSecretKey() {
    return secretKey;
  }


  public void setSecretKey(String secretKey) {
    this.secretKey = secretKey;
  }



   /**
   * The canonical user ID which is valid for user-owned buckets.
   * @return canonicalUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "a73e086eeaaa03e21e4e932ac8a2ed7a", value = "The canonical user ID which is valid for user-owned buckets.")

  public String getCanonicalUserId() {
    return canonicalUserId;
  }


  public void setCanonicalUserId(String canonicalUserId) {
    this.canonicalUserId = canonicalUserId;
  }



   /**
   * The contract user ID which is valid for contract-owned buckets.
   * @return contractUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "11111111:00000000-0000-0000-0000-000000000000", value = "The contract user ID which is valid for contract-owned buckets.")

  public String getContractUserId() {
    return contractUserId;
  }


  public void setContractUserId(String contractUserId) {
    this.contractUserId = contractUserId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessKey accessKey = (AccessKey) o;
    return Objects.equals(this.description, accessKey.description) && Objects.equals(this.accessKey, accessKey.accessKey) && Objects.equals(this.secretKey, accessKey.secretKey) && Objects.equals(this.canonicalUserId, accessKey.canonicalUserId) && Objects.equals(this.contractUserId, accessKey.contractUserId);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessKey {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");

    sb.append("    accessKey: ").append(toIndentedString(accessKey)).append("\n");

    sb.append("    secretKey: ").append(toIndentedString(secretKey)).append("\n");

    sb.append("    canonicalUserId: ").append(toIndentedString(canonicalUserId)).append("\n");

    sb.append("    contractUserId: ").append(toIndentedString(contractUserId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

