/*
 * IONOS Cloud - Object Storage Management API
 * Object Storage Management API is a RESTful API that manages the object storage service configuration for IONOS Cloud. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.objectstoragemanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ionoscloud.objectstoragemanagement.model.ErrorMessages;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * The Error object is used to represent an error response from the API. 
 */
@ApiModel(description = "The Error object is used to represent an error response from the API. ")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-26T10:43:43.862421Z[Etc/UTC]")

public class Error {
  
  public static final String SERIALIZED_NAME_HTTP_STATUS = "httpStatus";
  @SerializedName(SERIALIZED_NAME_HTTP_STATUS)
  private Integer httpStatus;


  public static final String SERIALIZED_NAME_MESSAGES = "messages";
  @SerializedName(SERIALIZED_NAME_MESSAGES)
  private List<ErrorMessages> messages = null;

  

  public Error httpStatus(Integer httpStatus) {
    
    this.httpStatus = httpStatus;
    return this;
  }

   /**
   * The HTTP status code of the operation.
   * @return httpStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "400", value = "The HTTP status code of the operation.")

  public Integer getHttpStatus() {
    return httpStatus;
  }


  public void setHttpStatus(Integer httpStatus) {
    this.httpStatus = httpStatus;
  }



  public Error messages(List<ErrorMessages> messages) {
    
    this.messages = messages;
    return this;
  }

  public Error addMessagesItem(ErrorMessages messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<ErrorMessages>();
    }
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * A list of error messages. 
   * @return messages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of error messages. ")

  public List<ErrorMessages> getMessages() {
    return messages;
  }


  public void setMessages(List<ErrorMessages> messages) {
    this.messages = messages;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Error error = (Error) o;
    return Objects.equals(this.httpStatus, error.httpStatus) && Objects.equals(this.messages, error.messages);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Error {\n");
    
    sb.append("    httpStatus: ").append(toIndentedString(httpStatus)).append("\n");

    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

