/*
 * IONOS Cloud - Object Storage Management API
 * Object Storage Management API is a RESTful API that manages the object storage service configuration for IONOS Cloud. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.objectstoragemanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * MetadataWithSupportedRegionsAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-26T11:53:54.572423Z[Etc/UTC]")

public class MetadataWithSupportedRegionsAllOf {
  
  public static final String SERIALIZED_NAME_SUPPORTED_REGIONS = "supportedRegions";
  @SerializedName(SERIALIZED_NAME_SUPPORTED_REGIONS)
  private List<String> supportedRegions = new ArrayList<String>();

  

  public MetadataWithSupportedRegionsAllOf supportedRegions(List<String> supportedRegions) {
    
    this.supportedRegions = supportedRegions;
    return this;
  }

  public MetadataWithSupportedRegionsAllOf addSupportedRegionsItem(String supportedRegionsItem) {
    this.supportedRegions.add(supportedRegionsItem);
    return this;
  }

   /**
   * The list of supported regions. 
   * @return supportedRegions
  **/
  @ApiModelProperty(example = "[\"de\",\"eu-central-2\",\"eu-south-2\"]", required = true, value = "The list of supported regions. ")

  public List<String> getSupportedRegions() {
    return supportedRegions;
  }


  public void setSupportedRegions(List<String> supportedRegions) {
    this.supportedRegions = supportedRegions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetadataWithSupportedRegionsAllOf metadataWithSupportedRegionsAllOf = (MetadataWithSupportedRegionsAllOf) o;
    return Objects.equals(this.supportedRegions, metadataWithSupportedRegionsAllOf.supportedRegions);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetadataWithSupportedRegionsAllOf {\n");
    
    sb.append("    supportedRegions: ").append(toIndentedString(supportedRegions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

