/*
 * IONOS Cloud - Object Storage Management API
 * Object Storage Management API is a RESTful API that manages the object storage service configuration for IONOS Cloud. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.objectstoragemanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MetadataWithStatusAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-26T16:27:52.335721Z[Etc/UTC]")

public class MetadataWithStatusAllOf {
  
  /**
   * The status of the object. The status can be: * &#x60;AVAILABLE&#x60; - resource exists and is healthy. * &#x60;PROVISIONING&#x60; - resource is being created or updated. * &#x60;DESTROYING&#x60; - delete command was issued, the resource is being deleted. * &#x60;FAILED&#x60; - resource failed, details in &#x60;failureMessage&#x60;. 
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    PROVISIONING("PROVISIONING"),
    
    DESTROYING("DESTROYING"),
    
    AVAILABLE("AVAILABLE"),
    
    FAILED("FAILED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {

      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status;


  public static final String SERIALIZED_NAME_STATUS_MESSAGE = "statusMessage";
  @SerializedName(SERIALIZED_NAME_STATUS_MESSAGE)
  private String statusMessage;


  public static final String SERIALIZED_NAME_ADMINISTRATIVE = "administrative";
  @SerializedName(SERIALIZED_NAME_ADMINISTRATIVE)
  private Boolean administrative;

  

   /**
   * The status of the object. The status can be: * &#x60;AVAILABLE&#x60; - resource exists and is healthy. * &#x60;PROVISIONING&#x60; - resource is being created or updated. * &#x60;DESTROYING&#x60; - delete command was issued, the resource is being deleted. * &#x60;FAILED&#x60; - resource failed, details in &#x60;failureMessage&#x60;. 
   * @return status
  **/
  @ApiModelProperty(example = "AVAILABLE", required = true, value = "The status of the object. The status can be: * `AVAILABLE` - resource exists and is healthy. * `PROVISIONING` - resource is being created or updated. * `DESTROYING` - delete command was issued, the resource is being deleted. * `FAILED` - resource failed, details in `failureMessage`. ")

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }



   /**
   * The message of the failure if the status is &#x60;FAILED&#x60;. 
   * @return statusMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The message of the failure if the status is `FAILED`. ")

  public String getStatusMessage() {
    return statusMessage;
  }


  public void setStatusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
  }



   /**
   * Indicates if the key is an administrative key. Administrative keys can create buckets and set bucket policies. 
   * @return administrative
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Indicates if the key is an administrative key. Administrative keys can create buckets and set bucket policies. ")

  public Boolean getAdministrative() {
    return administrative;
  }


  public void setAdministrative(Boolean administrative) {
    this.administrative = administrative;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetadataWithStatusAllOf metadataWithStatusAllOf = (MetadataWithStatusAllOf) o;
    return Objects.equals(this.status, metadataWithStatusAllOf.status) && Objects.equals(this.statusMessage, metadataWithStatusAllOf.statusMessage) && Objects.equals(this.administrative, metadataWithStatusAllOf.administrative);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetadataWithStatusAllOf {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");

    sb.append("    statusMessage: ").append(toIndentedString(statusMessage)).append("\n");

    sb.append("    administrative: ").append(toIndentedString(administrative)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

