/*
 * IONOS Cloud - Object Storage Management API
 * Object Storage Management API is a RESTful API that manages the object storage service configuration for IONOS Cloud. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.objectstoragemanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The capabilities of the region
 */
@ApiModel(description = "The capabilities of the region")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-26T10:43:43.862421Z[Etc/UTC]")

public class RegionCapability {
  
  public static final String SERIALIZED_NAME_IAM = "iam";
  @SerializedName(SERIALIZED_NAME_IAM)
  private Boolean iam;


  public static final String SERIALIZED_NAME_S3SELECT = "s3select";
  @SerializedName(SERIALIZED_NAME_S3SELECT)
  private Boolean s3select;

  

  public RegionCapability iam(Boolean iam) {
    
    this.iam = iam;
    return this;
  }

   /**
   * Indicates if IAM policy based access is supported
   * @return iam
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Indicates if IAM policy based access is supported")

  public Boolean getIam() {
    return iam;
  }


  public void setIam(Boolean iam) {
    this.iam = iam;
  }



  public RegionCapability s3select(Boolean s3select) {
    
    this.s3select = s3select;
    return this;
  }

   /**
   * Indicates if S3 Select is supported
   * @return s3select
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Indicates if S3 Select is supported")

  public Boolean getS3select() {
    return s3select;
  }


  public void setS3select(Boolean s3select) {
    this.s3select = s3select;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegionCapability regionCapability = (RegionCapability) o;
    return Objects.equals(this.iam, regionCapability.iam) && Objects.equals(this.s3select, regionCapability.s3select);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegionCapability {\n");
    
    sb.append("    iam: ").append(toIndentedString(iam)).append("\n");

    sb.append("    s3select: ").append(toIndentedString(s3select)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

