/*
 * IONOS Cloud - Object Storage Management API
 * Object Storage Management API is a RESTful API that manages the object storage service configuration for IONOS Cloud. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.objectstoragemanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ionoscloud.objectstoragemanagement.model.Links;
import com.ionoscloud.objectstoragemanagement.model.Pagination;
import com.ionoscloud.objectstoragemanagement.model.RegionRead;
import com.ionoscloud.objectstoragemanagement.model.RegionReadListAllOf;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * RegionReadList
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-25T14:47:08.560494Z[Etc/UTC]")

public class RegionReadList {
  
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;


  /**
   * The type of the resource.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    COLLECTION("collection");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {

      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;


  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private String href;


  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  private List<RegionRead> items = null;


  public static final String SERIALIZED_NAME_OFFSET = "offset";
  @SerializedName(SERIALIZED_NAME_OFFSET)
  private Integer offset;


  public static final String SERIALIZED_NAME_LIMIT = "limit";
  @SerializedName(SERIALIZED_NAME_LIMIT)
  private Integer limit;


  public static final String SERIALIZED_NAME_LINKS = "_links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private Links links;

  

  public RegionReadList id(UUID id) {
    
    this.id = id;
    return this;
  }

   /**
   * ID of the list of Region resources.
   * @return id
  **/
  @ApiModelProperty(example = "1bcda4f5-f78b-532d-976d-183e3437af91", required = true, value = "ID of the list of Region resources.")

  public UUID getId() {
    return id;
  }


  public void setId(UUID id) {
    this.id = id;
  }



  public RegionReadList type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * The type of the resource.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "The type of the resource.")

  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }



  public RegionReadList href(String href) {
    
    this.href = href;
    return this;
  }

   /**
   * The URL of the list of Region resources.
   * @return href
  **/
  @ApiModelProperty(example = "/regions", required = true, value = "The URL of the list of Region resources.")

  public String getHref() {
    return href;
  }


  public void setHref(String href) {
    this.href = href;
  }



  public RegionReadList items(List<RegionRead> items) {
    
    this.items = items;
    return this;
  }

  public RegionReadList addItemsItem(RegionRead itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<RegionRead>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * The list of Region resources.
   * @return items
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The list of Region resources.")

  public List<RegionRead> getItems() {
    return items;
  }


  public void setItems(List<RegionRead> items) {
    this.items = items;
  }



   /**
   * The offset specified in the request (if none was specified, the default offset is 0). 
   * minimum: 0
   * @return offset
  **/
  @ApiModelProperty(example = "0", required = true, value = "The offset specified in the request (if none was specified, the default offset is 0). ")

  public Integer getOffset() {
    return offset;
  }


  public void setOffset(Integer offset) {
    this.offset = offset;
  }



   /**
   * The limit specified in the request (if none was specified, use the endpoint&#39;s default pagination limit). 
   * minimum: 0
   * @return limit
  **/
  @ApiModelProperty(example = "42", required = true, value = "The limit specified in the request (if none was specified, use the endpoint's default pagination limit). ")

  public Integer getLimit() {
    return limit;
  }


  public void setLimit(Integer limit) {
    this.limit = limit;
  }



  public RegionReadList links(Links links) {
    
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(required = true, value = "")

  public Links getLinks() {
    return links;
  }


  public void setLinks(Links links) {
    this.links = links;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegionReadList regionReadList = (RegionReadList) o;
    return Objects.equals(this.id, regionReadList.id) && Objects.equals(this.type, regionReadList.type) && Objects.equals(this.href, regionReadList.href) && Objects.equals(this.items, regionReadList.items) && Objects.equals(this.offset, regionReadList.offset) && Objects.equals(this.limit, regionReadList.limit) && Objects.equals(this.links, regionReadList.links);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegionReadList {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");

    sb.append("    type: ").append(toIndentedString(type)).append("\n");

    sb.append("    href: ").append(toIndentedString(href)).append("\n");

    sb.append("    items: ").append(toIndentedString(items)).append("\n");

    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");

    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");

    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

