/*
 * IONOS Cloud - Object Storage Management API
 * Object Storage Management API is a RESTful API that manages the object storage service configuration for IONOS Cloud. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.objectstoragemanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ionoscloud.objectstoragemanagement.model.RegionCapability;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * IONOS Cloud object storage regions they define the location of the bucket, can also be used as &#x60;LocationConstraint&#x60; for bucket creation. 
 */
@ApiModel(description = "IONOS Cloud object storage regions they define the location of the bucket, can also be used as `LocationConstraint` for bucket creation. ")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-26T11:50:15.750085Z[Etc/UTC]")

public class Region {
  
  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private Integer version;


  public static final String SERIALIZED_NAME_ENDPOINT = "endpoint";
  @SerializedName(SERIALIZED_NAME_ENDPOINT)
  private String endpoint;


  public static final String SERIALIZED_NAME_WEBSITE = "website";
  @SerializedName(SERIALIZED_NAME_WEBSITE)
  private String website;


  public static final String SERIALIZED_NAME_CAPABILITY = "capability";
  @SerializedName(SERIALIZED_NAME_CAPABILITY)
  private RegionCapability capability;


  public static final String SERIALIZED_NAME_STORAGE_CLASSES = "storageClasses";
  @SerializedName(SERIALIZED_NAME_STORAGE_CLASSES)
  private List<String> storageClasses = null;


  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private String location;

  

  public Region version(Integer version) {
    
    this.version = version;
    return this;
  }

   /**
   * The version of the region properties
   * @return version
  **/
  @ApiModelProperty(example = "1", required = true, value = "The version of the region properties")

  public Integer getVersion() {
    return version;
  }


  public void setVersion(Integer version) {
    this.version = version;
  }



  public Region endpoint(String endpoint) {
    
    this.endpoint = endpoint;
    return this;
  }

   /**
   * The endpoint URL for the region
   * @return endpoint
  **/
  @ApiModelProperty(example = "s3.eu-central-1.ionoscloud.com", required = true, value = "The endpoint URL for the region")

  public String getEndpoint() {
    return endpoint;
  }


  public void setEndpoint(String endpoint) {
    this.endpoint = endpoint;
  }



  public Region website(String website) {
    
    this.website = website;
    return this;
  }

   /**
   * The website URL for the region
   * @return website
  **/
  @ApiModelProperty(example = "s3-website-de-central.profitbricks.com", required = true, value = "The website URL for the region")

  public String getWebsite() {
    return website;
  }


  public void setWebsite(String website) {
    this.website = website;
  }



  public Region capability(RegionCapability capability) {
    
    this.capability = capability;
    return this;
  }

   /**
   * Get capability
   * @return capability
  **/
  @ApiModelProperty(required = true, value = "")

  public RegionCapability getCapability() {
    return capability;
  }


  public void setCapability(RegionCapability capability) {
    this.capability = capability;
  }



  public Region storageClasses(List<String> storageClasses) {
    
    this.storageClasses = storageClasses;
    return this;
  }

  public Region addStorageClassesItem(String storageClassesItem) {
    if (this.storageClasses == null) {
      this.storageClasses = new ArrayList<String>();
    }
    this.storageClasses.add(storageClassesItem);
    return this;
  }

   /**
   * The available classes in the region
   * @return storageClasses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[\"standard\",\"standardInfrequentAccess\"]", value = "The available classes in the region")

  public List<String> getStorageClasses() {
    return storageClasses;
  }


  public void setStorageClasses(List<String> storageClasses) {
    this.storageClasses = storageClasses;
  }



  public Region location(String location) {
    
    this.location = location;
    return this;
  }

   /**
   * The data center location of the region as per [Get Location](/docs/cloud/v6/#tag/Locations/operation/locationsGet). *Can&#39;t be used as &#x60;LocationConstraint&#x60; on bucket creation.* 
   * @return location
  **/
  @ApiModelProperty(example = "de/fra", required = true, value = "The data center location of the region as per [Get Location](/docs/cloud/v6/#tag/Locations/operation/locationsGet). *Can't be used as `LocationConstraint` on bucket creation.* ")

  public String getLocation() {
    return location;
  }


  public void setLocation(String location) {
    this.location = location;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Region region = (Region) o;
    return Objects.equals(this.version, region.version) && Objects.equals(this.endpoint, region.endpoint) && Objects.equals(this.website, region.website) && Objects.equals(this.capability, region.capability) && Objects.equals(this.storageClasses, region.storageClasses) && Objects.equals(this.location, region.location);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Region {\n");
    
    sb.append("    version: ").append(toIndentedString(version)).append("\n");

    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");

    sb.append("    website: ").append(toIndentedString(website)).append("\n");

    sb.append("    capability: ").append(toIndentedString(capability)).append("\n");

    sb.append("    storageClasses: ").append(toIndentedString(storageClasses)).append("\n");

    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

