/*
 * IONOS Cloud - Object Storage Management API
 * Object Storage Management API is a RESTful API that manages the object storage service configuration for IONOS Cloud. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.objectstoragemanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Details the cross functional aspects of the given storage class. 
 */
@ApiModel(description = "Details the cross functional aspects of the given storage class. ")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-26T10:43:43.862421Z[Etc/UTC]")

public class StorageClass {
  
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;


  public static final String SERIALIZED_NAME_DURABILITY = "durability";
  @SerializedName(SERIALIZED_NAME_DURABILITY)
  private String durability;


  public static final String SERIALIZED_NAME_AVAILABILITY = "availability";
  @SerializedName(SERIALIZED_NAME_AVAILABILITY)
  private String availability;

  

  public StorageClass description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Explains the motivation for the storage class
   * @return description
  **/
  @ApiModelProperty(required = true, value = "Explains the motivation for the storage class")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }



  public StorageClass durability(String durability) {
    
    this.durability = durability;
    return this;
  }

   /**
   * The durability of the storage class
   * @return durability
  **/
  @ApiModelProperty(example = "99.999999999", required = true, value = "The durability of the storage class")

  public String getDurability() {
    return durability;
  }


  public void setDurability(String durability) {
    this.durability = durability;
  }



  public StorageClass availability(String availability) {
    
    this.availability = availability;
    return this;
  }

   /**
   * The availability of the storage class
   * @return availability
  **/
  @ApiModelProperty(example = "99.99", required = true, value = "The availability of the storage class")

  public String getAvailability() {
    return availability;
  }


  public void setAvailability(String availability) {
    this.availability = availability;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StorageClass storageClass = (StorageClass) o;
    return Objects.equals(this.description, storageClass.description) && Objects.equals(this.durability, storageClass.durability) && Objects.equals(this.availability, storageClass.availability);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StorageClass {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");

    sb.append("    durability: ").append(toIndentedString(durability)).append("\n");

    sb.append("    availability: ").append(toIndentedString(availability)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

