/*
 * IONOS Cloud - Object Storage Management API
 * Object Storage Management API is a RESTful API that manages the object storage service configuration for IONOS Cloud. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.objectstoragemanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ionoscloud.objectstoragemanagement.model.StorageClassRead;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * StorageClassReadListAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-26T16:27:52.335721Z[Etc/UTC]")

public class StorageClassReadListAllOf {
  
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;


  /**
   * The type of the resource.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    COLLECTION("collection");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {

      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;


  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private String href;


  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  private List<StorageClassRead> items = null;

  

  public StorageClassReadListAllOf id(UUID id) {
    
    this.id = id;
    return this;
  }

   /**
   * ID of the list of StorageClass resources.
   * @return id
  **/
  @ApiModelProperty(example = "965ebaca-6089-5961-ac9f-5ac94498bf3f", required = true, value = "ID of the list of StorageClass resources.")

  public UUID getId() {
    return id;
  }


  public void setId(UUID id) {
    this.id = id;
  }



  public StorageClassReadListAllOf type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * The type of the resource.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "The type of the resource.")

  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }



  public StorageClassReadListAllOf href(String href) {
    
    this.href = href;
    return this;
  }

   /**
   * The URL of the list of StorageClass resources.
   * @return href
  **/
  @ApiModelProperty(example = "/storageclasses", required = true, value = "The URL of the list of StorageClass resources.")

  public String getHref() {
    return href;
  }


  public void setHref(String href) {
    this.href = href;
  }



  public StorageClassReadListAllOf items(List<StorageClassRead> items) {
    
    this.items = items;
    return this;
  }

  public StorageClassReadListAllOf addItemsItem(StorageClassRead itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<StorageClassRead>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * The list of StorageClass resources.
   * @return items
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The list of StorageClass resources.")

  public List<StorageClassRead> getItems() {
    return items;
  }


  public void setItems(List<StorageClassRead> items) {
    this.items = items;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StorageClassReadListAllOf storageClassReadListAllOf = (StorageClassReadListAllOf) o;
    return Objects.equals(this.id, storageClassReadListAllOf.id) && Objects.equals(this.type, storageClassReadListAllOf.type) && Objects.equals(this.href, storageClassReadListAllOf.href) && Objects.equals(this.items, storageClassReadListAllOf.items);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StorageClassReadListAllOf {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");

    sb.append("    type: ").append(toIndentedString(type)).append("\n");

    sb.append("    href: ").append(toIndentedString(href)).append("\n");

    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

